blog/urls.py
from django.urls import path
from .views import render_post, post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_post, name='post'),
    path('<int:post_id>', post_detail, name='post_detail'),
    
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', views.home, name='index'),
    path('blog/',include('blog.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView
from django.contrib.auth.views import LoginView, logout_then_login

urlpatterns= [
    path('register/', RegisterView.as_view(), name='register'),
    path('accounts/login/', LoginView.as_view(), name="login"),
    path('logout/', logout_then_login, name='logout'),

]

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=150)
    decription = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date= models.DateField(datetime.date.today)

users/models.py
from django.db import models

# Create your models here.
class ProjectRegister(models.Model):
    
    title = models.CharField(max_length=50) 
    description =  models.TextField()
    tags = models.CharField(max_length=50)
    url = models.URLField(max_length=30)
    image = models.ImageField(upload_to='portfolio/images')

    def __str__(self):
        return self.title

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import ProjectRegister
#creamos clase para crear usuarios 
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        
        model = User
        
        fields = ("username", "first_name", "last_name", "email",  "password1", "password2")

    
    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        # aumentar el email
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class InputProject(forms.Form):
    title = forms.CharField(max_length=50)
    description = forms.TextInput()
    url = forms.URLField(max_length=30)
    image = forms.ImageField(allow_empty_file=True)
    tags= forms.CharField(max_length=10) 
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_post(request):
    posts = Post.objects.all()
    return render(request, 'post.html', {'posts' : posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk = post_id)    
    return render(request, 'post_detail.html', {'post':post}) 

users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.shortcuts import redirect
from .forms import NewUserForm
from .models import ProjectRegister

# Create your views here.
class RegisterView(CreateView):
  template_name = "registration/register.html"
  form_class = NewUserForm

  def form_valid(self, form):
      form.save()
      return redirect('login')

def home(request):
    projects = ProjectRegister.objects.all()
    return render(request, 'index.html', {'projects': projects})

blog/templates/post.html
{% extends 'layout.html' %}

{% block content %}


<h1>Post</h1>


{% for post in posts %}

    <h2><a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a></h2>
    <p>{{post.decription|striptags|truncatechars:100}}</p>
    <h3>{{post.date|date:'M d Y'}}</h3>
    <img src="{{post.image.url}}" alt="{{post.title}}">

    

{% endfor %}

{% endblock %}

blog/templates/post_detail.html
{% extends 'layout.html'%}

{% block content%}

<h1>Post</h1>

<h2>{{post.title}}</h2>
<h3>{{post.date}}</h3>
<p>{{post.decription|safe}}</p>
<img src="{{post.image.url}}" alt="{{post.title}}">

{% endblock %}

users/templates/index.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="rwo  bg-black">
    <div class="col-md-4">
<img src="{% static 'portfolio/profile.jpg'%}" alt="">
    </div>
    <div class="col-md-8 my-auto">
        <h1>I am <strong>Angel Fernandez</strong> </h1>
        <h3>I am Python Backend Developer</h3>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum quidem laboriosam quisquam beatae quis! Laboriosam eaque tenetur, rem adipisci blanditiis magnam error esse iusto molestiae eius saepe, quisquam ipsam totam recusandae itaque quo soluta tempore eveniet. Temporibus possimus accusamus exercitationem aperiam culpa voluptatum iusto vero nemo nobis, necessitatibus quaerat quasi ab nisi delectus numquam? Consequatur nisi, illum accusantium quidem corporis autem soluta alias beatae dolore modi obcaecati voluptatem fugit voluptas adipisci impedit ullam incidunt repellat saepe eveniet, hic error porro nobis. Ipsa, reiciendis culpa aperiam sequi accusamus magnam praesentium maxime et autem inventore, vel temporibus voluptates architecto eaque expedita corrupti?</p>
        

    </div>


</header>



<div class="row my-4 text-center">

    <h3>My Projects</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, ipsum maiores praesentium aliquam dolorum quam illo pariatur recusandae! Magnam, accusantium?</p>
    {% for project in projects %}
<div class="col md-4 p-4">
    <div class="card bg-black card-project" >
        <div class="card-body">

        <h2>{{project.title}}</h2>
        
        <p>{{project.description}}</p>
        <img src="{{project.image.url}}" alt="{{project.title}}" class="img-fluid">
        {% if project.url %}
        
        <a href="{{project.url}}">{{project.url}}</a>
        
        {% endif %}
        </div>
    </div>

</div>


{% endfor %}

{% endblock %}
</div>

users/templates/layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Angel's Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css ' %}">
</head>
<body class="text-light">
    
    
    {% include 'partials/navbar.html'%}
    
    
    <div class="container p-5">
        {%block content%}
        {% endblock%}


    </div>

     

    
 
    
</body>
</html>

users/templates/partials/navbar.html
{% load static%}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold fst-italic" href="/">Angel Fernandez</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Portfolio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog/">Blog</a>
          </li>
                  <li class="nav-item">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv.pdf' %}" target="_blank">Download CV</a>
          </li>
          
          </li>
        </ul>
      </div>
    </div>
  </nav>